# ETL
Now I'll start the ETL process for the data given.

First of all I'll import the libraries and the data.

In [30]:
import pandas as pd
import warnings

# First I load the .csv files
file1 = 'data/1728311703514.csv'
file2 = 'data/1728311703515.csv'

df_properties = pd.read_csv(file1)
df_bookings = pd.read_csv(file2)

warnings.simplefilter(action='ignore', category=FutureWarning)

And now I'll start cleaning and transforming the data.

In [31]:
# Then I clean and transform the data

# Cleaning the properties dataset
df_properties['ReadyDate'] = pd.to_datetime(df_properties['ReadyDate'], errors='coerce')  # Convert ReadyDate to datetime
df_properties['Square'] = pd.to_numeric(df_properties['Square'], errors='coerce')  # Ensure Square is numeric

# Cleaning the bookings dataset
df_bookings['BookingCreatedDate'] = pd.to_datetime(df_bookings['BookingCreatedDate'], errors='coerce')  # Convert to datetime
df_bookings['ArrivalDate'] = pd.to_datetime(df_bookings['ArrivalDate'], errors='coerce')  # Convert to datetime
df_bookings['DepartureDate'] = pd.to_datetime(df_bookings['DepartureDate'], errors='coerce')  # Convert to datetime
df_bookings['RoomRate'] = pd.to_numeric(df_bookings['RoomRate'], errors='coerce')  # Ensure RoomRate is numeric
df_bookings['CleaningFee'] = pd.to_numeric(df_bookings['CleaningFee'], errors='coerce')  # Ensure CleaningFee is numeric

# Now I merge both datasets on PropertyId
merged_df = pd.merge(df_properties, df_bookings, on='PropertyId', how='inner')  # Use inner join to combine data

# I display some info about the merged data
merged_df.head()

,PropertyId,RealProperty,Capacity,Square,PropertyType,NumBedrooms,ReadyDate,Property_BookingId,BookingCreatedDate,ArrivalDate,...,Infants,Persons,NumNights,Channel,RoomRate,CleaningFee,Revenue,ADR,TouristTax,TotalPaid
0,43630,Yes,7,141,Apartment,3,2024-09-25,155098,2024-10-02 20:06:48,2024-11-13,...,0,6,3,Airbnb,768.71,0.0,768.71,256.24,123.75,892.46
1,43630,Yes,7,141,Apartment,3,2024-09-25,155080,2024-10-02 15:51:02,2024-10-06,...,0,5,2,Airbnb,647.51,0.0,647.51,323.76,68.75,716.26
2,43630,Yes,7,141,Apartment,3,2024-09-25,154981,2024-10-01 00:11:52,2024-11-16,...,0,5,5,Airbnb,1045.01,0.0,1045.01,209.00,171.88,1216.89
3,43630,Yes,7,141,Apartment,3,2024-09-25,154799,2024-09-28 15:42:03,2024-10-04,...,0,6,2,Airbnb,901.51,0.0,901.51,450.76,72.60,974.11
4,43630,Yes,7,141,Apartment,3,2024-09-25,154796,2024-09-28 15:08:26,2024-10-08,...,0,4,3,Airbnb,661.51,0.0,661.51,220.50,54.45,715.96

Now once merged I'll start cleaning the data further.

In [32]:
# Fill null values in merged_df

# Categorical columns
merged_df['PropertyType'].fillna('Unknown', inplace=True)  # Fill with 'Unknown'
merged_df['PropertyType'].replace('Apa', 'Apartment', inplace=True) # Change the misstyped values
merged_df['Channel'].fillna(merged_df['Channel'].mode()[0], inplace=True)  # Fill with the mode

# Numerical columns
merged_df['RoomRate'].fillna(merged_df['RoomRate'].mean(), inplace=True)
merged_df['Revenue'].fillna(merged_df['Revenue'].mean(), inplace=True)
merged_df['ADR'].fillna(merged_df['ADR'].mean(), inplace=True)
merged_df['TouristTax'].fillna(merged_df['TouristTax'].mean(), inplace=True) 

# Datetime columns
merged_df['BookingCreatedDate'].fillna(merged_df['ArrivalDate'], inplace=True) # Fill BookingCreatedDate with ArrivalDate where BookingCreatedDate is null

# Optionally, check for any remaining null values
print(merged_df.isnull().sum())

# Save the merged dataset to a new CSV file
merged_df.to_csv('data/properties_bookings.csv', index=False)

PropertyId            0
RealProperty          0
Capacity              0
Square                0
PropertyType          0
NumBedrooms           0
ReadyDate             0
Property_BookingId    0
BookingCreatedDate    0
ArrivalDate           0
DepartureDate         0
Adults                0
Children              0
Infants               0
Persons               0
NumNights             0
Channel               0
RoomRate              0
CleaningFee           0
Revenue               0
ADR                   0
TouristTax            0
TotalPaid             0
dtype: int64